apiVersion: apps/v1
kind: Deployment
metadata:
  name: remixlearn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: remixlearn
  template:
    metadata:
      labels:
        app: remixlearn
    spec:
      containers:
      - name: remixlearn
        image: amigoscode/springboot-react-fullstack
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090


---

apiVersion: v1
kind: Service
metadata:
  name: remixlearn
spec:
  type: NodePort
  selector:
    app: remixlearn
  ports:
  - port: 909
    targetPort: 9090
